----------------------DIRTY READ-------------
-------------TH1
-------KHÁCH HÀNG XEM GIÁ NHÀ BÁN-----
CREATE PROC CHECK_PRICE_SOLVE @MANHA INT
AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL READ COMMITTED
	SELECT GiaBan FROM NhaBan
	WHERE MaNha = @MANHA
COMMIT TRAN

EXEC CHECK_PRICE_SOLVE 2






-----TH2---------------
--------KHÁCH HÀNG XEM THÔNG TIN CỦA 1 HỢP ĐỒNG
CREATE PROC SEE_CONTRACT_SOLVE @MAHOPDONG INT, @MANHA INT, @MAKH INT
AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL READ COMMITTED
	SELECT* FROM HopDongThue
	WHERE MaHopDong = @MAHOPDONG AND MaNha = @MANHA AND MaKH = @MAKH
COMMIT TRAN

EXEC SEE_CONTRACT_SOLVE 13, 10, 1









--------TH3----------------
-----------KHÁCH HÀNG XEM DANH SÁCH NHÀ BÁN
CREATE PROC SEE_HOUSE_FOR_SELL_SOLVE
AS
BEGIN TRAN	
	SET TRAN ISOLATION LEVEL READ COMMITTED
	SELECT* FROM NhaBan
COMMIT TRAN

EXEC SEE_HOUSE_FOR_SELL_SOLVE

-----------------------UNREPEATABLE READ------------
------------TH1
---------NHÂN VIÊN CẬP NHẬT TÌNH TRẠNG NHÀ TRÊN ĐƯỜNG
CREATE PROC UPDATE_STATUS_BY_STREET_SOLVE @TINHTRANG CHAR(50), @TENDUONG_NHA CHAR(50)
AS
BEGIN TRAN
	UPDATE Nha SET TinhTrang = @TINHTRANG WHERE TenDuong_Nha = @TENDUONG_NHA
COMMIT TRAN

EXEC UPDATE_STATUS_BY_STREET_SOLVE 'kin', 'Bach Dang'
SELECT TinhTrang FROM Nha WHERE TenDuong_Nha = 'Bach Dang'





-----------TH2
------------KHÁCH HÀNG TÌM DANH SÁCH NHÀ BÁN NHỎ HƠN GIÁ NHẬP VÀO
CREATE PROC FIND_HOUSE_WITH_PRICE_SOLVE @PRICE FLOAT
AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL REPEATABLE READ
	SELECT MaNha, GiaBan FROM NhaBan WHERE GiaBan < @PRICE
	WAITFOR DELAY '00:00:05'
	SELECT* FROM dbo.NhaBan WHERE GiaBan < @PRICE
COMMIT TRAN

EXEC FIND_HOUSE_WITH_PRICE_SOLVE 90000000

----------------------LOST UPDATE--------------------
------------TH1
----------NHÂN VIÊN CẬP NHẬT TÌNH TRẠNG NHÀ--------
CREATE PROC UPDATE_STATUS_01_SOLVE @MANHA INT, @STATUS CHAR(10)
AS
BEGIN TRAN

	DECLARE @STATUS_HOME CHAR(10)
	SET @STATUS_HOME = (SELECT TinhTrang FROM Nha 
					WHERE MaNha = @MANHA)
	SET @STATUS_HOME = @STATUS
	UPDATE Nha SET TinhTrang = @STATUS_HOME WHERE MaNha = @MANHA
COMMIT TRAN
DROP PROC dbo.UPDATE_STATUS_01_SOLVE
EXEC UPDATE_STATUS_01 1, 'het han'
SELECT TinhTrang FROM Nha


-------------------PHANTOM--------------
---------TH1
------KHÁCH HÀNG XEM TẤT CẢ HỢP ĐỒNG THUÊ CỦA MÌNH
CREATE PROC SEE_ALL_CONTRACT_SOLVE @MAKH INT
AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL SERIALIZABLE
	SELECT MaNha FROM HopDongThue WHERE MaKH = @MAKH
	WAITFOR DELAY '00:00:05'
	SELECT* FROM HopDongThue WHERE MaKH = @MAKH
COMMIT TRAN

EXEC SEE_ALL_CONTRACT_SOLVE 5


--------TH2
-------ADMIN THÊM 1 NHÂN VIÊN VÀO CHI NHÁNH
CREATE PROC AddEmployee_Solve @IDBranch INT, @name CHAR(50), @add CHAR(100), @sdt CHAR(11), @gender BIT,
			@DoB DATE, @salary FLOAT, @flag BIT, @user CHAR(50), @pass CHAR(50)
AS 
	BEGIN TRAN 
	INSERT INTO dbo.NhanVien
	(MaNV, MaCN, TenNV, DiaChiNV, SDT_NV, GioiTinhNV,
	 NgaySinh, Luong, CurrentFlag, username, password)
	 VALUES((SELECT COUNT(*) FROM dbo.NhanVien) + 1, @IDBranch, @name, @add, @sdt, @gender,
	 @DoB, @salary, @flag, @user, @pass)
COMMIT TRAN

EXEC AddEmployee_Solve  7, 'Vu' , 'TPHCM',
'0945614513', 0, '2000-11-17', 20000, 1, 'th', '123'

-----------------------CONVERSION DEADLOCK--------------
-----------TH1
---------NHÂN VIÊN CẬP NHẬT TÌNH TRẠNG NHÀ
----TỪ trong THÀNH het han
CREATE PROC UPDATE_STATUS_01_CONVERSION_DL_SOLVE @MANHA INT, @STATUS01 CHAR(10)
AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL SERIALIZABLE
	DECLARE @STATUS_HOUSE CHAR(10) = (SELECT TinhTrang FROM Nha
					WHERE MaNha = @MANHA)
	SET @STATUS_HOUSE = @STATUS01
	UPDATE Nha SET TinhTrang = @STATUS_HOUSE
	WHERE MaNha = @MANHA
COMMIT TRAN

EXEC UPDATE_STATUS_01_CONVERSION_DL_SOLVE 1, 'het han'
SELECT TinhTrang FROM Nha


-------------------CYCLE DEADLOCK-----------
------------TH1
ALTER PROC CYCLE_DL_01_SOLVE @MAKH INT, @MAPHIEU INT, @DIACHI CHAR(100), @TIEUCHI CHAR(100) 
AS
BEGIN TRAN
	--SET TRAN ISOLATION LEVEL SERIALIZABLE
	UPDATE KhachHang SET DiaChiKH = @DIACHI
	WHERE MaKH = @MAKH  
	UPDATE YeuCauKhachHang  SET TieuChi = @TIEUCHI
	WHERE MaKH = @MAKH AND MaPhieu = @MAPHIEU

COMMIT TRAN

EXEC CYCLE_DL_01_SOLVE 3, 2, 'Long An', 'co gac'
